### ISSUE TITLE
_config.yml missing

### ISSUE THREAD

**Issue by francoisbruneau** [andrewbanchich/Future-Imperfect-Jekyll-Theme#1]
Hello!
I would love to try your theme but the "_config.yml" file is missing from the root directory. Would it be possible for you to add it?
Many thanks in advance,
François

**Comment by andrewbanchich** [comment]
@francoisbruneau I actually haven't gotten to finishing this one yet. I think most of them are complete, but I still have to finish this one's Jekyllfication.
