### ISSUE TITLE
Needs _config.yml?

### ISSUE THREAD

**Issue by ryanstraits** [andrewbanchich/future-imperfect-jekyll-theme#2]
Thanks for creating this Jekyll version of Future Imperfect. Am I missing something or is there a reason why there is no _config.yml in this repo? Noticed that most of your other Jekyll HTML5UP conversions do have them, so I wanted to check. Thanks!

**Comment by andrewbanchich** [comment]
You're welcome! I put WIP in the title of any that are "works in progress" because they're aren't full functional yet. This is one I haven't gotten to work on much which is why it's missing that file. I will hopefully get to it soon, though.

**Comment by ryanstraits** [comment]
Cool, gotcha. Think copying one of the _config.yml files from one of your other HTML5UP Jekyll ports would work? Or are their other aspects of this theme that aren't functional yet?

**Comment by andrewbanchich** [comment]
There's a lot of functionality I haven't added to this one yet, so I don't think that would do anything. Sorry!

**Comment by ryanstraits** [comment]
Ah, fair enough. Well I'll follow along for when you are able to get them done! Again, appreciate the work. I'm assuming the ones that don't have (WIP) in the title are fully functional?

**Comment by andrewbanchich** [comment]
Correct!
